name: Terraform Plan

on:
  pull_request:
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.CICD_SA }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7"

      - name: Terraform Init
        run: terraform init -backend-config="bucket=emmanuel-portfolio-agent-tfstate"
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -var-file="envs/prod/terraform.tfvars"
        working-directory: infra